name: Build regular-gnome-atomic.iso

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to build'
        required: true
        default: 'regular-gnome-atomic.iso'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: nisel11/alt-image-builder@1.1.1
        with:
          image: ${{ github.event.inputs.image }}
